"""add_resume_filename_hash_to_application_and_profile

Revision ID: 03e74396e693
Revises: 5b58a4eb507e
Create Date: 2026-05-21 10:50:23.043886

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03e74396e693"
down_revision: Union[str, Sequence[str], None] = "5b58a4eb507e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column(
            "resume_filename",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "application",
        sa.Column(
            "resume_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
    )
    op.add_column(
        "candidateprofile",
        sa.Column(
            "resume_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidateprofile", "resume_hash")
    op.drop_column("application", "resume_hash")
    op.drop_column("application", "resume_filename")
    # ### end Alembic commands ###
