"""add_login_lockout_columns_to_user

Revision ID: 5f57f1a7cc38
Revises: 03e74396e693
Create Date: 2026-05-21 17:48:09.666037

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f57f1a7cc38"
down_revision: Union[str, Sequence[str], None] = "03e74396e693"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "failed_login_attempts", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "user", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "locked_until")
    op.drop_column("user", "failed_login_attempts")
    # ### end Alembic commands ###
