"""add used_refresh_token table

Revision ID: 6e26d8b21e9c
Revises: 23cb6a11a8da
Create Date: 2026-06-05 16:00:05.213562

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e26d8b21e9c"
down_revision: Union[str, Sequence[str], None] = "23cb6a11a8da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usedrefreshtoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usedrefreshtoken_token_hash"),
        "usedrefreshtoken",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_usedrefreshtoken_user_id"),
        "usedrefreshtoken",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usedrefreshtoken_user_id"), table_name="usedrefreshtoken")
    op.drop_index(op.f("ix_usedrefreshtoken_token_hash"), table_name="usedrefreshtoken")
    op.drop_table("usedrefreshtoken")
    # ### end Alembic commands ###
