"""add_contract_pdf_url_to_companyprofile

Revision ID: afc9218a03de
Revises: b3c7d9e1f2a4
Create Date: 2026-05-05 19:24:20.507376

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afc9218a03de"
down_revision: Union[str, Sequence[str], None] = "b3c7d9e1f2a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companyprofile",
        sa.Column("contract_pdf_url", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companyprofile", "contract_pdf_url")
    # ### end Alembic commands ###
