"""Add unique constraint on Application (job_id, candidate_id)

Revision ID: ce657d1f111d
Revises: e2dcba4df8fb
Create Date: 2026-01-17 22:24:28.818802

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce657d1f111d"
down_revision: Union[str, Sequence[str], None] = "e2dcba4df8fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_application_job_candidate", "application", ["job_id", "candidate_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_application_job_candidate", "application", type_="unique")
    # ### end Alembic commands ###
