"""Add Job, CandidateProfile, and Application models

Revision ID: e2dcba4df8fb
Revises: 1fd9cd5dc2a8
Create Date: 2026-01-17 20:40:31.952297

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2dcba4df8fb"
down_revision: Union[str, Sequence[str], None] = "1fd9cd5dc2a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidateprofile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("resume_path", sa.String(), nullable=True),
        sa.Column("linkedin_url", sa.String(), nullable=True),
        sa.Column("service_concept", sa.Text(), nullable=True),
        sa.Column("salary_expectations", sa.Text(), nullable=True),
        sa.Column("military_service_details", sa.Text(), nullable=True),
        sa.Column("transportation", sa.Text(), nullable=True),
        sa.Column("personality_weakness", sa.Text(), nullable=True),
        sa.Column("personality_strength", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidateprofile_email"), "candidateprofile", ["email"], unique=True
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("requirements", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING_APPROVAL", "PUBLISHED", "CLOSED", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companyprofile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_company_id"), "job", ["company_id"], unique=False)
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "APPROVED_BY_ADMIN",
                "REJECTED",
                "HIRED",
                name="applicationstatus",
            ),
            nullable=False,
        ),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidateprofile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_candidate_id"),
        "application",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_job_id"), "application", ["job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_job_id"), table_name="application")
    op.drop_index(op.f("ix_application_candidate_id"), table_name="application")
    op.drop_table("application")
    op.drop_index(op.f("ix_job_company_id"), table_name="job")
    op.drop_table("job")
    op.drop_index(op.f("ix_candidateprofile_email"), table_name="candidateprofile")
    op.drop_table("candidateprofile")
    # ### end Alembic commands ###
